controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

contact:
    path:       /contact
    controller: 'App\Controller\DefaultController::contact'
    condition:  "context.getMethod() in ['GET', 'HEAD'] and request.headers.get('User-Agent') matches '/firefox/i'"
    # expressions can also include configuration parameters:
    # condition: "request.headers.get('User-Agent') matches '%app.allowed_browsers%'"
    # expressions can even use environment variables:
    # condition: "context.getHost() == env('APP_MAIN_HOST')"

post_show:
    path:       /posts/{id}
    controller: 'App\Controller\DefaultController::showPost'
    # expressions can retrieve route parameter values using the "params" variable
    condition:  "params['id'] < 1000"

app_logout:
    path: /api/logout
    methods: GET

api_login_check:
    path: /api/login_check